name: "Split test notification bot"

description: "Split test notification bot"
inputs:
  sites:
    description: "Send a slack notification about a new release"
    required: true
  slackToken:
    description: "Slack Token"
    required: true
  slackChannel:
    description: "Slack Channel"
    required: true
  github-token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
  branch:
    description: |
      The name of the branch from which the pull request was opened. For cross-repository pull requests namespace the
      branch with user or organization name, i.e. 'user:branch-name' or 'org:branch-name'.
    required: false
  base:
    description: 'The base branch name of the Pull Request'
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
